import { ArrowDownRight, ArrowRight, Building2, ChartNoAxesCombined, Check, Eye, FileSearch, FlaskConical, LockKeyhole, ShieldCheck, SlidersHorizontal, TriangleAlert } from "lucide-react";

const app = process.env.NEXT_PUBLIC_APP_URL ?? "http://localhost:3100";
function Brand() { return <a className="brand" href="/" aria-label="Blaubeere home"><span className="brand-mark" aria-hidden><i/><i/><i/><i/></span>blaubeere</a>; }

export default function Home() {
  return <><a href="#main" className="skip-link">Skip to content</a><header className="site-header site-container"><Brand/><nav aria-label="Main navigation"><a href="#how-it-works">How it works</a><a href="#planning">Planning</a><a href="#built-for-finance">Built for finance</a></nav><a className="button secondary" href={`${app}/login`}>Open workspace<ArrowRight size={16} aria-hidden/></a></header>
    <main id="main"><section className="hero site-container"><div className="hero-copy"><span className="hero-eyebrow"><span className="live-dot"/>Financial foresight, made clear</span><h1>Make room<br/>for <em>what’s next.</em></h1><p>See cash shortfalls before they become difficult decisions. Turn your company’s financial picture into a plan you can explain.</p><div className="hero-actions"><a className="button" href={`${app}/dashboard`}>See your cash outlook<ArrowRight size={17} aria-hidden/></a><a className="button ghost" href="#how-it-works">Take a closer look<ArrowDownRight size={17} aria-hidden/></a></div><span className="hero-footnote"><LockKeyhole size={13} aria-hidden/>Your companies. Your assumptions. Your decisions.</span></div>
      <div className="hero-visual"><div className="preview-grid" aria-hidden/><div className="preview"><div className="preview-header"><span><Building2 size={15} aria-hidden/><strong>Mediterránea Supply</strong></span><span className="badge accent">Cash outlook</span></div><div className="preview-stats"><div><span className="eyebrow">Cash today</span><strong className="num">€2.0m</strong><small>31 August 2026</small></div><div><span className="eyebrow">Funding needed</span><strong className="num">€2.1m</strong><small>Above a €100k floor</small></div></div>
        <div className="preview-chart"><svg viewBox="0 0 450 205" role="img" aria-label="Illustrative cash outlook: cash falls from two million euros to negative two million on 28 September before recovering in October."><path d="M36 30H430M36 80H430M36 130H430M36 180H430" stroke="var(--line)"/><text x="0" y="34">€2m</text><text x="0" y="134">€0</text><line x1="36" x2="430" y1="126" y2="126" stroke="var(--warn)" strokeDasharray="3 5"/><path d="M36 38H150V182H185V154H220V170H243V43H283V58H325V40H368V55H430V35" fill="none" stroke="var(--accent)" strokeWidth="2.5" strokeDasharray="5 3"/><circle cx="150" cy="182" r="4" fill="var(--bad)"/><text x="36" y="202">31 Aug</text><text x="175" y="202">30 Sept</text><text x="306" y="202">30 Oct</text><text x="390" y="202">29 Nov</text></svg></div><div className="preview-alert"><TriangleAlert size={18} aria-hidden/><div><strong>A cash gap ahead, not a surprise.</strong>Supplier payments fall before customer receipts.</div></div></div><p className="preview-caption">Illustrative 90-day outlook · demo data</p></div>
    </section>
    <div className="principles site-container"><span><ChartNoAxesCombined size={17} aria-hidden/>Cash pressure comes first</span><span><Eye size={17} aria-hidden/>Every assumption stays visible</span><span><ShieldCheck size={17} aria-hidden/>Access stays with your team</span></div>
    <section className="workflow site-container" id="how-it-works"><div className="section-intro"><div><span className="eyebrow">From a number to a next step</span><h2>A clearer picture.<br/>A more considered plan.</h2></div><p>One focused workspace for the questions that matter to your finance team.</p></div><div className="workflow-grid">
      <article className="workflow-step"><span className="mono">01 / ASSESS</span><h3>Know where you stand.</h3><p>See usable cash, upcoming obligations, and the first potential shortfall. Follow the trajectory, with financial health as context.</p><div className="step-detail"><ChartNoAxesCombined size={16} aria-hidden/>30, 60 and 90-day checkpoints</div></article>
      <article className="workflow-step"><span className="mono">02 / UNDERSTAND</span><h3>Follow the evidence.</h3><p>Trace changes back to dated sources. See where timings are estimated, history is reconstructed, or information is missing.</p><div className="step-detail"><FileSearch size={16} aria-hidden/>A reason behind each number</div></article>
      <article className="workflow-step"><span className="mono">03 / EXPLORE</span><h3>Put your options to work.</h3><p>Choose a target and deadline. Compare changes to collections, spending and funding, with cash constraints checked every day.</p><div className="step-detail"><SlidersHorizontal size={16} aria-hidden/>Baseline plus two conditional plans</div></article>
    </div></section>
    <section className="planning-section" id="planning"><div className="planning-inner site-container"><div className="planning-copy"><span className="eyebrow">Ambition, with a cash floor</span><h2>“What would it take?”<br/>is a good place to start.</h2><p>Protect a cash buffer. Fund the next quarter. Explore a revenue goal with your own business assumptions. See the trade-offs before you choose.</p><a className="button" href={`${app}/dashboard`}>Explore a plan<ArrowRight size={16} aria-hidden/></a></div><div className="mini-plan"><span className="badge accent"><FlaskConical size={13} aria-hidden/>An example, not a promise</span><h3>Keep cash above €100,000</h3><p>Through 29 November · every day of the plan</p><div className="mini-plan-row"><span>Collection timing</span><strong>Up to 14 days earlier</strong></div><div className="mini-plan-row"><span>Discretionary spend</span><strong>Up to 10% lower</strong></div><div className="mini-plan-row"><span>Additional funding</span><strong>Within your limit</strong></div><div className="mini-plan-note"><Check size={17} aria-hidden/><span>Compare the cash impact and remaining gaps. Source records and observed health stay unchanged.</span></div></div></div></section>
    <section className="trust site-container" id="built-for-finance"><div><span className="eyebrow">Built for the people behind the numbers</span><h2>Clear about what’s known.<br/>Honest about what isn’t.</h2></div><div className="trust-list"><div><FileSearch size={21} aria-hidden/><div><h3>Evidence you can inspect</h3><p>Dated cash flows, visible assumptions and missing inputs. A projection is only useful when you understand what’s in it.</p></div></div><div><ShieldCheck size={21} aria-hidden/><div><h3>A workspace for your companies</h3><p>Company access is enforced by the backend. Connected assistants use the same permissions and can be disconnected at any time.</p></div></div><div><SlidersHorizontal size={21} aria-hidden/><div><h3>Decisions stay with your team</h3><p>Test scenarios without changing source data or executing payments. If a tested plan falls short, see the gap that remains.</p></div></div></div></section>
    <section className="closing site-container"><h2>Ahead of the gap.<br/>Ready for the conversation.</h2><p>Bring a clearer cash picture to your next finance meeting.</p><a className="button" href={`${app}/dashboard`}>Open your workspace<ArrowRight size={16} aria-hidden/></a></section></main>
    <footer className="site-footer site-container"><Brand/><span>Financial foresight for your next decision. · HackSpain 2026</span><a href={`${app}/login`}>Sign in<ArrowRight size={13} className="inline ml-2" aria-hidden/></a></footer>
  </>;
}
