"use client";
import Link from "next/link";
import { useEffect, useRef, useState } from "react";
import { ArrowLeft, ArrowRight, Activity, Database } from "lucide-react";
import { date, money } from "../lib/format";
import { healthHref } from "../lib/health";
import { cashScale } from "./cash-chart";
import type { CompanySummary, ModelAssessment, ModelRecord } from "../lib/types";

export const modelNumber = (value: number | null | undefined, suffix = "") => value == null ? "Not available" : `${new Intl.NumberFormat("en-GB", { maximumFractionDigits: 1 }).format(value)}${suffix}`;
const euro = (value: number | null | undefined) => value == null ? "Not available" : money(Math.round(value * 100), "EUR", false, true);
const confidence: Record<string, string> = { alta: "High", media: "Medium", baja: "Low", ninguna: "None" };
export function modelReason(reason: string) {
  const unknown = reason.match(/^([cpd])_eur_desconocido_en_(\d+)_meses$/);
  if (unknown) return `${({ c: "Collections", p: "Operating payments", d: "Debt service" } as Record<string, string>)[unknown[1]]} could not be fully determined in ${unknown[2]} month(s) of the window.`;
  return ({ sin_colchon_estimado: "No cash cushion could be estimated.", sin_mora_observable: "Payment arrears were not observable; no arrears adjustment was applied.", colchon_saturado: "The cash cushion reached the model's cap.", denominador_nulo: "No calculable flow ratio for this window.", sin_actividad_de_caja_observada: "No cash-account activity was observed.", ventana_parcial: "The assessment uses fewer than six months of history.", r_hist_indefinida: "The historical ratio was undefined; the history adjustment was omitted.", sin_actividad_en_ventana: "No cash activity was observed in this window." } as Record<string,string>)[reason] ?? reason;
}
function ScoreChart({ records, company }: { records: ModelRecord[]; company: string }) {
  const [width, setWidth] = useState(1000);
  const svg = useRef<SVGSVGElement>(null);
  useEffect(() => {
    const observer = new ResizeObserver(([entry]) => setWidth(Math.max(240, entry.contentRect.width)));
    if (svg.current) observer.observe(svg.current);
    return () => observer.disconnect();
  }, []);
  const right = width - 20;
  const x = (index: number) => 42 + index * (right - 42) / Math.max(1, records.length - 1);
  const y = (score: number) => 218 - score * 1.9;
  const path = records.map((row, index) => row.health_score === null ? "" : `${index && records[index - 1].health_score !== null ? "L" : "M"}${x(index)},${y(row.health_score)}`).join(" ");
  return <div className="model-chart"><svg ref={svg} viewBox={`0 0 ${width} 258`} role="img" aria-labelledby="model-chart-title model-chart-description"><title id="model-chart-title">Monthly health score history</title><desc id="model-chart-description">Saved model ratings from 0 to 100. Gaps mean no score was returned. Select a dated rating below for its explanation.</desc>{[0,25,50,75,100].map(value => <g key={value}><line x1="42" x2={right} y1={y(value)} y2={y(value)} stroke="var(--line)"/><text x="30" y={y(value)+4} textAnchor="end">{value}</text></g>)}<path d={path} fill="none" stroke="var(--accent)" strokeWidth="2.5"/>{records.map((row,index) => row.health_score === null ? null : <a key={row.as_of} href={healthHref(company,row.as_of)} aria-label={`${date(row.as_of,true)}: score ${modelNumber(row.health_score)}`}><circle cx={x(index)} cy={y(row.health_score)} r={width < 540 ? 3 : 5} fill="var(--surface)" stroke="var(--accent)" strokeWidth="2"/></a>)}{records.filter((_,index) => index===0 || index===records.length-1 || (width > 540 && index===Math.floor(records.length/2))).map(row => <text key={row.as_of} x={x(records.indexOf(row))} y="246" textAnchor={row===records[0]?"start":row===records.at(-1)?"end":"middle"}>{date(row.as_of,true)}</text>)}</svg><p className="chart-note">Monthly observations. Missing ratings stay empty; no daily scores are interpolated.</p></div>;
}

function MonthlyCashChart({ records, row, onMonth }: { records: ModelRecord[]; row: ModelRecord; onMonth: (date: string) => void }) {
  const [metric, setMetric] = useState<"flujo_neto" | "posicion_acumulada">("flujo_neto");
  const [width, setWidth] = useState(1000);
  const svg = useRef<SVGSVGElement>(null);
  useEffect(() => {
    const observer = new ResizeObserver(([entry]) => setWidth(Math.max(280, entry.contentRect.width)));
    if (svg.current) observer.observe(svg.current);
    return () => observer.disconnect();
  }, [records]);
  const values = records.map(record => record.cash?.[metric] == null ? null : Math.round(record.cash[metric]! * 100));
  const known = values.filter((value): value is number => value !== null);
  const { min, max, ticks } = cashScale(Math.min(0, ...known), Math.max(0, ...known));
  const right = width - 20;
  const x = (index: number) => 78 + index * (right - 78) / Math.max(1, records.length - 1);
  const y = (value: number) => 230 - (value - min) / (max - min) * 200;
  const selected = records.indexOf(row);
  const selectedValue = values[selected];
  const path = values.map((value, index) => value === null ? "" : `${index && values[index - 1] !== null ? "L" : "M"}${x(index)},${y(value)}`).join(" ");
  return <section className="card monthly-cash" aria-labelledby="monthly-cash-title">
    <div className="card-heading"><div><h2 id="monthly-cash-title">Cash movements over time</h2><p className="small muted mt-1">Recorded movements through {date(records.at(-1)!.as_of, true)}.</p></div><div className="monthly-chart-mode"><label htmlFor="cash-metric">Show</label><select id="cash-metric" className="control" value={metric} onChange={event => setMetric(event.target.value as typeof metric)}><option value="flujo_neto">Monthly net movement</option><option value="posicion_acumulada">Cumulative movement</option></select></div></div>
    <div className="model-chart">
      {known.length ? <svg ref={svg} viewBox={`0 0 ${width} 274`} role="img" aria-labelledby="monthly-chart-title monthly-chart-description">
        <title id="monthly-chart-title">{metric === "flujo_neto" ? "Monthly net cash movements" : "Cumulative cash movements from the observed start"}</title>
        <desc id="monthly-chart-description">Amounts in EUR. Gaps indicate unavailable records. Use the month control below to inspect the data. Cumulative movements are not a bank balance.</desc>
        {ticks.map(value => <g key={value}><line x1="78" x2={right} y1={y(value)} y2={y(value)} stroke={value === 0 ? "var(--subtle)" : "var(--line)"}/><text x="65" y={y(value) + 4} textAnchor="end">{money(value, "EUR", true)}</text></g>)}
        <path d={path} fill="none" stroke="var(--accent)" strokeWidth="2.5"/>
        {values.map((value, index) => value === null ? null : <circle key={records[index].as_of} cx={x(index)} cy={y(value)} r={width < 540 ? 3 : 4} fill="var(--surface)" stroke="var(--accent)" strokeWidth="2"/>)}
        <line x1={x(selected)} x2={x(selected)} y1="25" y2="235" stroke="var(--accent)" strokeDasharray="4 4"/>
        {selectedValue !== null && <circle cx={x(selected)} cy={y(selectedValue)} r="6" fill="var(--accent)"/>}
        {records.filter((_, index) => index === 0 || index === records.length - 1 || (width > 540 && index === Math.floor(records.length / 2))).map(record => <text key={record.as_of} x={x(records.indexOf(record))} y="261" textAnchor={record === records[0] ? "start" : record === records.at(-1) ? "end" : "middle"}>{date(record.as_of, true)}</text>)}
      </svg> : <p className="monthly-empty">No cash movements were published for this company. Available scores and payment records are shown separately.</p>}
      <div className="chart-inspector"><div className="chart-controls"><label htmlFor="cash-month">Inspect month<input id="cash-month" type="range" min="0" max={records.length - 1} value={selected} aria-valuetext={`${date(row.as_of, true)}: ${euro(row.cash?.[metric])}`} onChange={event => onMonth(records[Number(event.target.value)].as_of)}/></label></div><output htmlFor="cash-month"><span>{date(row.as_of, true)}</span><strong className="num">{euro(row.cash?.[metric])}</strong></output></div>
      <p className="chart-note">Cumulative movement starts at zero in the first observed month. It is not a bank balance. Gaps stay unknown.</p>
    </div>
    <dl className="checkpoints"><div><dt className="eyebrow">Net movement this month</dt><dd className="num">{euro(row.cash?.flujo_neto)}</dd></div><div><dt className="eyebrow">Cumulative movement</dt><dd className="num">{euro(row.cash?.posicion_acumulada)}</dd></div><div><dt className="eyebrow">Estimated coverage</dt><dd className="num">{modelNumber(row.cash?.meses_de_cobertura, " months")}</dd></div></dl>
  </section>;
}

function MonthlyBreakdown({ row }: { row: ModelRecord }) {
  const cash = row.cash, payment = row.payment;
  const percent = (value: number | null | undefined) => modelNumber(value == null ? null : value * 100, "%");
  return <div className="monthly-breakdown">
    <section className="card monthly-detail"><h2>Cash movements · {date(row.as_of)}</h2><p className="small muted">Signed amounts in the published cash categories.</p><dl className="metric-equation">{[
      ["Operating inflows", cash?.flujo_operating_in], ["Operating outflows", cash?.flujo_operating_out],
      ["Financing inflows", cash?.flujo_financing_in], ["Financing outflows", cash?.flujo_financing_out],
      ["Investment inflows", cash?.flujo_investment_in], ["Investment outflows", cash?.flujo_investment_out],
      ["Transfers", cash?.flujo_transfer], ["Non-economic movements", cash?.flujo_non_economic], ["Unclassified movements", cash?.flujo_unknown],
    ].map(([label, value]) => <div key={String(label)}><dt>{label}</dt><dd className="num">{euro(value as number | null | undefined)}</dd></div>)}</dl><p className="small muted">Cash confidence: {cash ? confidence[cash.confidence] ?? cash.confidence : "Not available"}. These categories precede the model’s transfer-resolution adjustments, so they may differ from its rolling totals.</p>{cash?.flags.includes("agujeros_en_tramo") && <p className="model-note mt-4">Some movements have unknown EUR amounts. The reported totals cover known amounts only.</p>}</section>
    <section className="card monthly-detail"><h2>Payments and collections</h2><p className="small muted">Invoices due by {date(row.as_of, true)}. These are totals at the cutoff, not this month’s cash flows.</p><h3 className="mt-4">Supplier payments</h3><dl className="metric-equation">{[["Known amount due", euro(payment?.debido_eur)], ["Overdue at cutoff", euro(payment?.en_mora_en_el_corte_eur)], ["Overdue share", percent(payment?.mora_ratio)], ["Average paid delay", modelNumber(payment?.retraso_medio_dias_pagado, " days")]].map(([label, value]) => <div key={label}><dt>{label}</dt><dd className="num">{value}</dd></div>)}</dl><h3 className="mt-4">Customer collections</h3><dl className="metric-equation">{[["Known amount due", euro(payment?.cobro_debido_eur)], ["Overdue at cutoff", euro(payment?.cobro_en_mora_en_el_corte_eur)], ["Overdue share", percent(payment?.cobro_mora_ratio)], ["Average collected delay", modelNumber(payment?.cobro_retraso_medio_dias_pagado, " days")]].map(([label, value]) => <div key={label}><dt>{label}</dt><dd className="num">{value}</dd></div>)}</dl><p className="small muted">Payment confidence: {payment ? confidence[payment.confidence] ?? payment.confidence : "Not available"}. {payment ? `${payment.n_huecos_eur} invoice(s) with unknown EUR amounts; ${payment.n_vencimiento_desconocido} with unknown due dates.` : "No payment evidence was published for this month."} Historical cutoffs use invoice due dates; their original registration dates are unavailable.</p></section>
    <section className="card monthly-detail monthly-debt"><div><h2>Debt service in the model window</h2><p className="small muted">Known observed debt service across {row.n_meses_ventana} months ending {date(row.as_of, true)}. This is not the outstanding debt balance or a future repayment schedule.</p></div><dl className="metric-equation"><div><dt>Debt service (D6)</dt><dd className="num">{euro(row.d6)}</dd></div><div><dt>Operating payments (P6)</dt><dd className="num">{euro(row.p6)}</dd></div><div className="equation-result"><dt>Combined model payments (T6)</dt><dd className="num">{euro(row.t6)}</dd></div></dl></section>
  </div>;
}

function MonthlyRecords({ records, company, selected, onMonth }: { records: ModelRecord[]; company: string; selected: string; onMonth: (date: string) => void }) {
  return <section className="card monthly-records"><div className="card-heading"><div><h2>Monthly source records</h2><p className="small muted mt-1">Select a month to inspect its data, or open its score explanation.</p></div><span className="badge">{records.length} months</span></div><div className="table-scroll" role="region" aria-label="Monthly source records, scroll to inspect all columns" tabIndex={0}><table><caption className="sr-only">Published month-end scores, cash movements, payment arrears and rolling debt service in EUR</caption><thead><tr><th scope="col">Month end</th><th scope="col">Health score</th><th scope="col">Net movement</th><th scope="col">Cumulative movement</th><th scope="col">Overdue payments</th><th scope="col">Overdue collections</th><th scope="col">Debt service · window</th></tr></thead><tbody>{[...records].reverse().map(row => <tr key={row.as_of} data-selected={row.as_of === selected}><th scope="row"><button className="monthly-row-button" onClick={() => onMonth(row.as_of)} aria-pressed={row.as_of === selected}>{date(row.as_of, true)}</button></th><td><Link className="monthly-rating-link" href={healthHref(company, row.as_of)} aria-label={`Explain ${date(row.as_of, true)} rating: ${modelNumber(row.health_score)}`}>{modelNumber(row.health_score)}<ArrowRight size={14} aria-hidden/></Link></td><td className="num">{euro(row.cash?.flujo_neto)}</td><td className="num">{euro(row.cash?.posicion_acumulada)}</td><td className="num">{euro(row.payment?.en_mora_en_el_corte_eur)}</td><td className="num">{euro(row.payment?.cobro_en_mora_en_el_corte_eur)}</td><td className="num">{euro(row.d6)}<span>{row.n_meses_ventana} months</span></td></tr>)}</tbody></table></div></section>;
}

export function ModelDashboard({ data, scoreDate, companies, onCompany }: { data: ModelAssessment; scoreDate?: string; companies: CompanySummary[]; onCompany: (id: string) => void }) {
  const [month, setMonth] = useState(data.records.at(-1)?.as_of ?? "");
  const row = data.records.find(row => row.as_of === (scoreDate ?? month));
  const scoreHref = (day: string) => healthHref(data.company.id,day);
  const selectedIndex = row ? data.records.indexOf(row) : -1;
  const previous = data.records[selectedIndex - 1];
  const next = data.records[selectedIndex + 1];
  const delta = row?.health_score != null && previous?.health_score != null ? row.health_score - previous.health_score : null;
  return <div className="model-dashboard">
    <p className="sr-only" role="status">{row ? `Showing data for ${date(row.as_of, true)}` : "No assessment selected"}</p>
    <header className="page-heading"><div><div className="eyebrow mb-2">Published model assessments</div><h1>{scoreDate ? "The story behind this rating." : "Your financial health, over time."}</h1><p className="muted mt-2">{data.company.name} · {data.company.group} · model inputs in EUR</p></div>{scoreDate && <Link className="button secondary" href={`/dashboard?company=${encodeURIComponent(data.company.id)}`}><ArrowLeft size={16} aria-hidden/>Overview</Link>}</header>
    <div className="context-row"><label className="sr-only" htmlFor="model-company">Company</label><select className="control" id="model-company" value={data.company.id} onChange={event=>onCompany(event.target.value)}>{companies.map(company=><option key={company.id} value={company.id}>{company.name}</option>)}</select><span className="badge accent"><Database size={13} aria-hidden/>X-Ray dataset</span><span className="small muted">{data.records.length} monthly assessments</span><label className="sr-only" htmlFor="model-date">Assessment date</label><select className="control" id="model-date" value={row?.as_of ?? ""} onChange={event=>scoreDate ? window.location.assign(scoreHref(event.target.value)) : setMonth(event.target.value)}>{!row && <option value="">Choose an assessment</option>}{[...data.records].reverse().map(record=><option key={record.as_of} value={record.as_of}>{date(record.as_of,true)} · {modelNumber(record.health_score)}</option>)}</select></div>
    {!row ? <section className="card metric-intro"><h2>No assessment for this date</h2><p>The model output is monthly. Choose a saved month-end assessment above.</p></section> : <>
      <section className="stats-grid model-stats" aria-label="Published assessment summary"><article className="stat-card"><div><span>Health score · {date(row.as_of)}</span><Activity size={17} aria-hidden/></div><Link className="model-score-link" href={scoreHref(row.as_of)}><strong className="stat-value num">{modelNumber(row.health_score)}</strong>{row.health_score !== null && <span> / 100</span>}<ArrowRight size={16} aria-hidden/></Link><p>{delta === null ? "No comparable previous score" : `${delta > 0 ? "+" : ""}${modelNumber(delta)} points since ${date(previous.as_of)}`}</p></article>{[["Known collections",row.c6],["Known operating payments",row.p6],["Known debt service",row.d6]].map(([label,value])=><article className="stat-card" key={String(label)}><div><span>{label}</span></div><strong className="stat-value num">{euro(value as number|null)}</strong><p>Across the {row.n_meses_ventana}-month model window</p></article>)}</section>
      <p className="model-context small muted">{row.version} · {date(row.as_of,true)} · Reported confidence: <strong>{confidence[row.confidence] ?? row.confidence}</strong>. Known subtotals can be incomplete; inspect the model reasons.</p>
      {!scoreDate ? <><MonthlyCashChart records={data.records} row={row} onMonth={setMonth}/><MonthlyBreakdown row={row}/><section className="card"><div className="card-heading"><div><h2>Health score history</h2><p className="small muted mt-1">Select a rating to inspect its recorded inputs and explanation.</p></div></div><ScoreChart records={data.records} company={data.company.id}/><div className="model-dates">{data.records.map(record=><Link key={record.as_of} href={scoreHref(record.as_of)}><strong className="num">{record.health_score === null ? "No score" : modelNumber(record.health_score)}</strong><span>{date(record.as_of,true)}</span></Link>)}</div></section><MonthlyRecords records={data.records} company={data.company.id} selected={row.as_of} onMonth={setMonth}/><p className="model-context small muted">Forecasting and planning need a verified opening cash balance and dated future obligations. This dataset supplies historical model outputs.</p></> : <section className="card health-assessment-card"><div className="metric-columns">
        <section className="metric-evidence"><div className="metric-section-heading"><h2>How the model reached this score</h2><span className="badge">{row.n_meses_ventana} months</span></div><p className="small muted">The model combines known collections, operating payments and debt service with a capped cash cushion and the company’s own historical ratio. Payment arrears can reduce the resulting rating.</p><dl className="metric-equation">{[["Known collections (C6)",euro(row.c6)],["Operating payments (P6)",euro(row.p6)],["Debt service (D6)",euro(row.d6)],["Combined known payments (T6)",euro(row.t6)],["Applicable cash cushion",euro(row.colchon_aplicable)],["Own historical collection ratio",modelNumber(row.r_hist===null?null:row.r_hist*100,"%")],["Historical adjustment (k)",row.r_hist===null?"Omitted":euro(row.k)],["Score before arrears",modelNumber(row.h_antes_de_mora)],["Arrears reduction",modelNumber(row.penalizacion_mora_puntos," points")],["Returned health score",modelNumber(row.health_score)]].map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl><details className="source-records"><summary>Formula and parameters</summary><div className="model-formula"><p>H = 100 × (C6 + cushion + k × historical ratio) / (C6 + cushion + T6 + k)</p><p>Final score = H × (1 − beta × payment arrears ratio)</p><p>k = {row.k} EUR · alpha = {row.alpha} · beta = {row.beta}. k is omitted when the historical ratio is undefined. The displayed score comes directly from the saved model output.</p></div></details><h2 className="mt-6">What limits this assessment</h2><ul className="model-reasons">{row.reasons.map(reason=><li key={reason}>{modelReason(reason)}</li>)}{!row.reasons.length && <li>No additional reason codes were returned.</li>}</ul>{row.p6===0 && row.health_score!==null && <p className="model-note">No operating payments were identified in this window. This published model can still return a rating, including 100; that does not establish perfect financial health.</p>}</section>
        <aside className="metric-explanation" aria-label="Supporting model inputs"><section><span className="eyebrow">Cash movements</span><h2>Relative to the observed start</h2><dl className="metric-equation"><div><dt>Cumulative movement</dt><dd>{euro(row.cash?.posicion_acumulada)}</dd></div><div><dt>This month’s net movement</dt><dd>{euro(row.cash?.flujo_neto)}</dd></div><div><dt>Observed start</dt><dd>{row.cash ? date(row.cash.mes_origen.slice(0,10),true):"Not available"}</dd></div><div><dt>Estimated coverage</dt><dd>{modelNumber(row.cash?.meses_de_cobertura," months")}</dd></div></dl><p className="small muted">This is cumulative movement since the first observed month, not a bank balance or usable cash today.</p></section><section><span className="eyebrow">Payment timing</span><h2>Obligations due at this cutoff</h2><dl className="metric-equation"><div><dt>Amount due</dt><dd>{euro(row.payment?.debido_eur)}</dd></div><div><dt>Overdue at cutoff</dt><dd>{euro(row.payment?.en_mora_en_el_corte_eur)}</dd></div><div><dt>Payment arrears ratio</dt><dd>{modelNumber(row.mora_ratio===null?null:row.mora_ratio*100,"%")}</dd></div><div><dt>Average paid delay</dt><dd>{modelNumber(row.payment?.retraso_medio_dias_pagado," days")}</dd></div></dl><p className="small muted">Unavailable inputs stay unknown. Missing payment history does not imply zero arrears.</p></section></aside>
      </div></section>}
      {scoreDate && <nav className="health-adjacent" aria-label="Other assessments">{previous?<Link className="button secondary" href={scoreHref(previous.as_of)}><ArrowLeft size={16} aria-hidden/>{date(previous.as_of,true)}</Link>:<span/>}{next&&<Link className="button secondary" href={scoreHref(next.as_of)}>{date(next.as_of,true)}<ArrowRight size={16} aria-hidden/></Link>}</nav>}
    </>}
    <section className="card model-provenance" id="evidence"><h2>Source data and model status</h2><p className="small muted">The challenge dataset is synthetic. These are the published v3 model outputs, with provisional parameters and known limitations; this is not a validated credit rating.</p><details><summary>Inspect imported sources and model limitations</summary><div className="model-source-list">{data.provenance.files.map(source=><div key={source.table}><strong>{source.path}</strong><span>{source.rows.toLocaleString("en-GB")} records · SHA-256 {source.sha256}</span></div>)}</div><p className="small muted">Imported {data.provenance.imported_at} · source commit {data.provenance.source_revision}</p><p className="small muted">{data.provenance.model_summary.advertencia}</p><ul className="model-reasons">{data.provenance.model_summary.limitaciones.map(reason=><li key={reason}>{reason}</li>)}</ul></details></section>
  </div>;
}
