"use client";
import Link from "next/link";
import { useEffect, useRef, useState } from "react";
import { ArrowLeft, ArrowRight, Database } from "lucide-react";
import { date, money } from "../lib/format";
import { healthHref } from "../lib/health";
import { cashScale } from "./cash-chart";
import type { ModelAssessment, ModelRecord } from "../lib/types";

export const modelNumber = (value: number | null | undefined, suffix = "", maximumFractionDigits = 1) => value == null ? "Not available" : `${new Intl.NumberFormat("en-GB", { maximumFractionDigits }).format(value)}${suffix}`;
const euro = (value: number | null | undefined) => value == null ? "Not available" : money(Math.round(value * 100), "EUR", false, true);
const confidence: Record<string, string> = { alta: "High", media: "Medium", baja: "Low", ninguna: "None", excluida: "Excluded" };
export function modelReason(reason: string) {
  const unknown = reason.match(/^([cpd]_eur|deficit_servicio_eur)_desconocido_en_(\d+)_meses$/);
  if (unknown) return `${({ c_eur: "Collections", p_eur: "Operating payments", d_eur: "Debt service", deficit_servicio_eur: "Debt-service shortfall" } as Record<string, string>)[unknown[1]]} could not be fully determined in ${unknown[2]} month(s) of the window.`;
  return ({
    excluida_nota_cero_persistente: "Excluded by the published v4 rule for persistently near-zero scores. This reflects uneven data coverage, not necessarily poor financial health; the company’s source records remain available.",
    sin_caja_reconstruida: "Cash could not be reconstructed; no cash cushion was applied.",
    saldo_reversa_negativo: "Reconstructed cash was negative, so the cash cushion is zero.",
    obligacion_vencida_desconocida: "Overdue obligations were unknown and omitted from the effective payment total.",
    multiplicador_deuda_desconocido: "The debt multiplier was unknown; no multiplier adjustment was applied.",
    pagos_operativos_no_demostrados: "No operating payments or positive overdue obligations were demonstrated, so no score was returned.",
    sin_flujos_observados_en_la_ventana: "No collections or effective payment obligations were observed in the model window.",
    nota_acotada_al_rango_0_100: "The returned score was bounded to the 0–100 range.",
    sin_colchon_estimado: "No cash cushion could be estimated.", sin_mora_observable: "Payment arrears were not observable; no arrears adjustment was applied.", colchon_saturado: "The cash cushion reached the model's cap.", denominador_nulo: "No calculable flow ratio for this window.", sin_actividad_de_caja_observada: "No cash-account activity was observed.", ventana_parcial: "The assessment uses fewer than six months of history.", r_hist_indefinida: "The historical ratio was undefined; the history adjustment was omitted.", sin_actividad_en_ventana: "No cash activity was observed in this window." } as Record<string,string>)[reason] ?? reason;
}
function ScoreChart({ records, row, onMonth }: { records: ModelRecord[]; row: ModelRecord; onMonth: (date: string) => void }) {
  const [width, setWidth] = useState(1000);
  const svg = useRef<SVGSVGElement>(null);
  useEffect(() => {
    const observer = new ResizeObserver(([entry]) => setWidth(Math.max(240, entry.contentRect.width)));
    if (svg.current) observer.observe(svg.current);
    return () => observer.disconnect();
  }, []);
  const right = width - 20;
  const x = (index: number) => 42 + index * (right - 42) / Math.max(1, records.length - 1);
  const y = (score: number) => 218 - score * 1.9;
  const path = records.map((row, index) => row.health_score === null ? "" : `${index && records[index - 1].health_score !== null ? "L" : "M"}${x(index)},${y(row.health_score)}`).join(" ");
  const selected = records.indexOf(row);
  return <div className="model-chart health-history-chart"><svg ref={svg} viewBox={`0 0 ${width} 258`} role="img" aria-labelledby="model-chart-title model-chart-description"><title id="model-chart-title">Monthly health score history</title><desc id="model-chart-description">Published model ratings from 0 to 100. Gaps mean no score was returned. Use the month control to inspect a rating and its source data.</desc>{[0,25,50,75,100].map(value => <g key={value}><line x1="42" x2={right} y1={y(value)} y2={y(value)} stroke="var(--line)"/><text x="30" y={y(value)+4} textAnchor="end">{value}</text></g>)}<path d={path} fill="none" stroke="var(--accent)" strokeWidth="2.5"/>{records.map((record,index) => record.health_score === null ? null : <circle key={record.as_of} cx={x(index)} cy={y(record.health_score)} r={record.as_of === row.as_of ? 6 : width < 540 ? 3 : 4} fill={record.as_of === row.as_of ? "var(--accent)" : "var(--surface)"} stroke="var(--accent)" strokeWidth="2"><title>{`${date(record.as_of,true)}: ${modelNumber(record.health_score)} / 100`}</title></circle>)}<line x1={x(selected)} x2={x(selected)} y1="18" y2="224" stroke="var(--accent)" strokeDasharray="4 4"/>{records.filter((_,index) => index===0 || index===records.length-1 || (width > 540 && index===Math.floor(records.length/2))).map(record => <text key={record.as_of} x={x(records.indexOf(record))} y="246" textAnchor={record===records[0]?"start":record===records.at(-1)?"end":"middle"}>{date(record.as_of,true)}</text>)}</svg>
    {!records.some(record => record.health_score !== null) && <p className="chart-note">No score was returned for this company. Its available source data is shown below.</p>}
    <div className="chart-inspector"><div className="chart-controls"><label htmlFor="health-month">Inspect month<input id="health-month" type="range" min="0" max={records.length - 1} value={selected} aria-valuetext={`${date(row.as_of,true)}: ${row.health_score === null ? "No score" : `${modelNumber(row.health_score)} out of 100`}`} onChange={event => onMonth(records[Number(event.target.value)].as_of)}/></label></div><output htmlFor="health-month"><span>{date(row.as_of,true)}</span><strong className="num">{row.health_score === null ? "No score" : `${modelNumber(row.health_score)} / 100`}</strong></output></div><p className="chart-note">Monthly observations. Missing ratings stay empty; no daily scores are interpolated.</p></div>;
}

function MonthlyCashChart({ records, row, onMonth }: { records: ModelRecord[]; row: ModelRecord; onMonth: (date: string) => void }) {
  const [metric, setMetric] = useState<"flujo_neto" | "saldo_reversa_eur">("flujo_neto");
  const [width, setWidth] = useState(1000);
  const svg = useRef<SVGSVGElement>(null);
  useEffect(() => {
    const observer = new ResizeObserver(([entry]) => setWidth(Math.max(280, entry.contentRect.width)));
    if (svg.current) observer.observe(svg.current);
    return () => observer.disconnect();
  }, [records, metric]);
  const values = records.map(record => record.cash?.[metric] == null ? null : Math.round(record.cash[metric]! * 100));
  const known = values.filter((value): value is number => value !== null);
  const { min, max, ticks } = cashScale(Math.min(0, ...known), Math.max(0, ...known));
  const right = width - 20;
  const x = (index: number) => 78 + index * (right - 78) / Math.max(1, records.length - 1);
  const y = (value: number) => 230 - (value - min) / (max - min) * 200;
  const selected = records.indexOf(row);
  const selectedValue = values[selected];
  const path = values.map((value, index) => value === null ? "" : `${index && values[index - 1] !== null ? "L" : "M"}${x(index)},${y(value)}`).join(" ");
  return <section className="card monthly-cash" id="cash" aria-labelledby="monthly-cash-title">
    <div className="card-heading"><div><h2 id="monthly-cash-title">Cash movements over time</h2><p className="small muted mt-1">Recorded movements through {date(records.at(-1)!.as_of, true)}.</p></div><div className="monthly-chart-mode"><label htmlFor="cash-metric">Show</label><select id="cash-metric" className="control" value={metric} onChange={event => setMetric(event.target.value as typeof metric)}><option value="flujo_neto">Monthly net movement</option><option value="saldo_reversa_eur">Reconstructed cash</option></select></div></div>
    <div className="model-chart">
      {known.length ? <svg ref={svg} viewBox={`0 0 ${width} 274`} role="img" aria-labelledby="monthly-chart-title monthly-chart-description">
        <title id="monthly-chart-title">{metric === "flujo_neto" ? "Monthly net cash movements" : "Cash reconstructed from the snapshot anchor"}</title>
        <desc id="monthly-chart-description">Amounts in EUR. Gaps indicate unavailable records. Use the month control below to inspect the data. Reconstructed cash is not a bank balance observed at the cutoff.</desc>
        {ticks.map(value => <g key={value}><line x1="78" x2={right} y1={y(value)} y2={y(value)} stroke={value === 0 ? "var(--subtle)" : "var(--line)"}/><text x="65" y={y(value) + 4} textAnchor="end">{money(value, "EUR", true)}</text></g>)}
        <path d={path} fill="none" stroke="var(--accent)" strokeWidth="2.5"/>
        {values.map((value, index) => value === null ? null : <circle key={records[index].as_of} cx={x(index)} cy={y(value)} r={width < 540 ? 3 : 4} fill="var(--surface)" stroke="var(--accent)" strokeWidth="2"/>)}
        <line x1={x(selected)} x2={x(selected)} y1="25" y2="235" stroke="var(--accent)" strokeDasharray="4 4"/>
        {selectedValue !== null && <circle cx={x(selected)} cy={y(selectedValue)} r="6" fill="var(--accent)"/>}
        {records.filter((_, index) => index === 0 || index === records.length - 1 || (width > 540 && index === Math.floor(records.length / 2))).map(record => <text key={record.as_of} x={x(records.indexOf(record))} y="261" textAnchor={record === records[0] ? "start" : record === records.at(-1) ? "end" : "middle"}>{date(record.as_of, true)}</text>)}
      </svg> : <p className="monthly-empty">No cash movements were published for this company. Available scores and payment records are shown separately.</p>}
      <div className="chart-inspector"><div className="chart-controls"><label htmlFor="cash-month">Inspect month<input id="cash-month" type="range" min="0" max={records.length - 1} value={selected} aria-valuetext={`${date(row.as_of, true)}: ${euro(row.cash?.[metric])}`} onChange={event => onMonth(records[Number(event.target.value)].as_of)}/></label></div><output htmlFor="cash-month"><span>{date(row.as_of, true)}</span><strong className="num">{euro(row.cash?.[metric])}</strong></output></div>
      <p className="chart-note">Cash is reconstructed backwards from the 1 September 2026 anchor. It is not a bank balance observed at each historical cutoff. Gaps stay unknown.</p>
    </div>
    <dl className="checkpoints"><div><dt className="eyebrow">Net movement this month</dt><dd className="num">{euro(row.cash?.flujo_neto)}</dd></div><div><dt className="eyebrow">Reconstructed cash</dt><dd className="num">{euro(row.cash?.saldo_reversa_eur)}</dd></div><div><dt className="eyebrow">Estimated coverage</dt><dd className="num">{modelNumber(row.cash?.meses_de_cobertura_reversa, " months")}</dd></div></dl>
  </section>;
}

function MonthlyBreakdown({ row }: { row: ModelRecord }) {
  const cash = row.cash, payment = row.payment;
  const index = (value: number | null | undefined) => modelNumber(value, " / 1", 3);
  return <div className="monthly-breakdown" id="payments">
    <section className="card monthly-detail"><h2>Cash movements · {date(row.as_of)}</h2><p className="small muted">Signed amounts in the published cash categories.</p><dl className="metric-equation">{[
      ["Operating inflows", cash?.flujo_operating_in], ["Operating outflows", cash?.flujo_operating_out],
      ["Financing inflows", cash?.flujo_financing_in], ["Financing outflows", cash?.flujo_financing_out],
      ["Investment inflows", cash?.flujo_investment_in], ["Investment outflows", cash?.flujo_investment_out],
      ["Transfers", cash?.flujo_transfer], ["Non-economic movements", cash?.flujo_non_economic], ["Unclassified movements", cash?.flujo_unknown],
    ].map(([label, value]) => <div key={String(label)}><dt>{label}</dt><dd className="num">{euro(value as number | null | undefined)}</dd></div>)}</dl><p className="small muted">Cash confidence: {cash ? confidence[cash.confidence] ?? cash.confidence : "Not available"}. These are the published cash-backfill categories; the model’s rolling totals also use transfer-resolution adjustments.</p>{cash?.flags.includes("agujeros_en_tramo") && <p className="model-note mt-4">Some movements have unknown EUR amounts. The reported totals cover known amounts only.</p>}</section>
    <section className="card monthly-detail"><h2>Payments and collections</h2><p className="small muted">Invoice evidence through {date(row.as_of, true)}. Exposure and overdue amounts are measured at the cutoff. The robust indices combine delay severity and persistence.</p><h3 className="mt-4">Supplier payments</h3><dl className="metric-equation">{[["Known invoice exposure", euro(payment?.pago_exposicion_eur)], ["Overdue at cutoff", euro(payment?.pago_vencido_eur)], ["Robust payment arrears index", index(payment?.mora_pago_robusta)]].map(([label, value]) => <div key={label}><dt>{label}</dt><dd className="num">{value}</dd></div>)}</dl><h3 className="mt-4">Customer collections</h3><dl className="metric-equation">{[["Known invoice exposure", euro(payment?.cobro_exposicion_eur)], ["Overdue at cutoff", euro(payment?.cobro_vencido_eur)], ["Robust collection arrears index", index(payment?.mora_cobro_robusta)]].map(([label, value]) => <div key={label}><dt>{label}</dt><dd className="num">{value}</dd></div>)}</dl><p className="small muted">Payment confidence: {payment ? confidence[payment.confidence] ?? payment.confidence : "Not available"}. {payment ? `${(payment.pago_n_huecos_eur + payment.cobro_n_huecos_eur)} invoice(s) with unknown EUR amounts; ${payment.n_vencimiento_desconocido} with unknown due dates.` : "No payment evidence was published for this month."} Historical cutoffs use invoice due dates; their original registration dates are unavailable.</p></section>
    <section className="card monthly-detail monthly-debt"><div><h2>Debt and overdue obligations</h2><p className="small muted">Observed debt service and service shortfalls span {row.n_meses_ventana} months ending {date(row.as_of, true)}. Overdue obligations are a stock at this cutoff, counted once. D6 is not the outstanding debt balance.</p></div><dl className="metric-equation"><div><dt>Debt service (D6)</dt><dd className="num">{euro(row.d6)}</dd></div><div><dt>Operating payments (P6)</dt><dd className="num">{euro(row.p6)}</dd></div><div><dt>Service shortfall · window</dt><dd className="num">{euro(row.deficit_servicio_6)}</dd></div><div><dt>Overdue obligations · cutoff</dt><dd className="num">{euro(row.obligacion_vencida_m)}</dd></div><div className="equation-result"><dt>Effective obligations (T6)</dt><dd className="num">{euro(row.t6_efectivo)}</dd></div></dl></section>
  </div>;
}

function MonthlyRecords({ records, company, selected, onMonth, demo }: { records: ModelRecord[]; company: string; selected: string; onMonth: (date: string) => void; demo: boolean }) {
  return <section className="card monthly-records" id="history"><div className="card-heading"><div><h2>Monthly source records</h2><p className="small muted mt-1">Select a month to inspect its data, or open its score explanation.</p></div><span className="badge">{records.length} months</span></div><div className="table-scroll" role="region" aria-label="Monthly source records, scroll to inspect all columns" tabIndex={0}><table><caption className="sr-only">Published month-end scores, cash movements, payment arrears and rolling debt service in EUR</caption><thead><tr><th scope="col">Month end</th><th scope="col">Health score</th><th scope="col">Net movement</th><th scope="col">Reconstructed cash</th><th scope="col">Overdue payments</th><th scope="col">Overdue collections</th><th scope="col">Debt service · window</th></tr></thead><tbody>{[...records].reverse().map(row => <tr key={row.as_of} data-selected={row.as_of === selected}><th scope="row"><button className="monthly-row-button" onClick={() => onMonth(row.as_of)} aria-pressed={row.as_of === selected}>{date(row.as_of, true)}</button></th><td><Link className="monthly-rating-link" href={healthHref(company, row.as_of, demo)} aria-label={`Explain ${date(row.as_of, true)} rating: ${modelNumber(row.health_score)}`}>{modelNumber(row.health_score)}<ArrowRight size={14} aria-hidden/></Link></td><td className="num">{euro(row.cash?.flujo_neto)}</td><td className="num">{euro(row.cash?.saldo_reversa_eur)}</td><td className="num">{euro(row.payment?.pago_vencido_eur)}</td><td className="num">{euro(row.payment?.cobro_vencido_eur)}</td><td className="num">{euro(row.d6)}<span>{row.n_meses_ventana} months</span></td></tr>)}</tbody></table></div></section>;
}

export function ModelDashboard({ data, scoreDate, demo = false }: { data: ModelAssessment; scoreDate?: string; demo?: boolean }) {
  const [month, setMonth] = useState(data.records.at(-1)?.as_of ?? "");
  const row = data.records.find(row => row.as_of === (scoreDate ?? month));
  const scoreHref = (day: string) => healthHref(data.company.id,day,demo);
  const selectedIndex = row ? data.records.indexOf(row) : -1;
  const previous = data.records[selectedIndex - 1];
  const next = data.records[selectedIndex + 1];
  const delta = row?.health_score != null && previous?.health_score != null ? row.health_score - previous.health_score : null;
  return <div className="model-dashboard">
    <p className="sr-only" role="status">{row ? `Showing data for ${date(row.as_of, true)}` : "No assessment selected"}</p>
    <header className="page-heading"><div><div className="eyebrow mb-2">{data.company.group} · EUR</div><h1>{scoreDate ? "The story behind this rating." : data.company.name}</h1><p className="muted mt-2">{scoreDate ? data.company.name : "Financial health and the movements behind it."}</p></div>{scoreDate && <Link className="button secondary" href={`${demo ? "/demo" : "/dashboard"}?company=${encodeURIComponent(data.company.id)}`}><ArrowLeft size={16} aria-hidden/>Overview</Link>}</header>
    <div className="context-row"><span className="badge accent"><Database size={13} aria-hidden/>Imported company data</span><span className="small muted">{data.records.length} monthly assessments</span><label className="sr-only" htmlFor="model-date">Assessment date</label><select className="control" id="model-date" value={row?.as_of ?? ""} onChange={event=>scoreDate ? window.location.assign(scoreHref(event.target.value)) : setMonth(event.target.value)}>{!row && <option value="">Choose an assessment</option>}{[...data.records].reverse().map(record=><option key={record.as_of} value={record.as_of}>{date(record.as_of,true)} · {modelNumber(record.health_score)}</option>)}</select></div>
    {!row ? <section className="card metric-intro"><h2>No assessment for this date</h2><p>The model output is monthly. Choose a saved month-end assessment above.</p></section> : <>
      <section className="card health-overview-panel" id="health" aria-labelledby="health-title">
        <div className="health-overview-main"><div className="card-heading"><div><h2 id="health-title">Health score</h2><p className="small muted mt-1">{scoreDate ? "Published rating at this cutoff" : "How the company’s cash-flow health has changed"}</p></div><span className="badge">{row.version}</span></div>
          <div className="health-selected-score"><strong className="num">{row.excluida ? "Excluded" : row.health_score === null ? "No score" : modelNumber(row.health_score)}</strong>{row.health_score !== null && <span>/ 100</span>}<div><span>{date(row.as_of,true)}</span><span>{delta === null ? "No comparable previous score" : `${delta > 0 ? "+" : ""}${modelNumber(delta)} points since ${date(previous.as_of)}`}</span></div></div>
          {!scoreDate && <ScoreChart records={data.records} row={row} onMonth={setMonth}/>}
        </div>
        <aside className="health-evidence-summary"><span className="eyebrow">Behind this rating</span><h3>Evidence at this cutoff</h3><dl className="metric-equation"><div><dt>Model confidence</dt><dd>{confidence[row.confidence] ?? row.confidence}</dd></div><div><dt>Observed months</dt><dd>{row.n_meses_con_actividad} of {row.n_meses_ventana}</dd></div><div><dt>Robust arrears index</dt><dd>{modelNumber(row.mora_indice, " / 1", 3)}</dd></div></dl><p className="small muted">{row.reasons.length ? modelReason(row.reasons[0]) : "No additional reason codes were returned."}</p><p className="small muted">Known subtotals can be incomplete. This is a provisional cash-flow score.</p>{!scoreDate && <Link className="button secondary" href={scoreHref(row.as_of)}>{row.health_score === null ? "Why no score?" : "Explain this score"}<ArrowRight size={16} aria-hidden/></Link>}</aside>
      </section>
      <section className="stats-grid model-stats" aria-label="Source data at the selected cutoff">{[["Monthly net movement",euro(row.cash?.flujo_neto),"Signed cash movement this month"],["Overdue supplier payments",euro(row.payment?.pago_vencido_eur),`Due and unpaid at ${date(row.as_of)}`],["Overdue customer collections",euro(row.payment?.cobro_vencido_eur),`Due and uncollected at ${date(row.as_of)}`],["Observed debt service",euro(row.d6),`Across the ${row.n_meses_ventana}-month model window`]].map(([label,value,caption])=><article className="stat-card" key={label}><div><span>{label}</span></div><strong className="stat-value num">{value}</strong><p>{caption}</p></article>)}</section>
      {!scoreDate ? <><MonthlyCashChart records={data.records} row={row} onMonth={setMonth}/><MonthlyBreakdown row={row}/><MonthlyRecords records={data.records} company={data.company.id} selected={row.as_of} onMonth={setMonth} demo={demo}/></> : <section className="card health-assessment-card"><div className="metric-columns">
        <section className="metric-evidence"><div className="metric-section-heading"><h2>How the model reached this score</h2><span className="badge">{row.n_meses_ventana} months</span></div><p className="small muted">The v4 model adds observed debt-service shortfalls and overdue obligations to known payments. It uses reconstructed cash for the cushion, then applies the robust arrears index and debt multiplier. Unknown inputs remain omitted and disclosed.</p><dl className="metric-equation">{[["Known collections (C6)",euro(row.c6)],["Operating payments (P6)",euro(row.p6)],["Debt service (D6)",euro(row.d6)],["Debt-service shortfall · window",euro(row.deficit_servicio_6)],["Overdue obligations · cutoff",euro(row.obligacion_vencida_m)],["Effective obligations (T6)",euro(row.t6_efectivo)],["Reconstructed cash cushion",euro(row.colchon_v4)],["Applicable cash cushion",euro(row.colchon_aplicable)],["Own historical collection ratio",modelNumber(row.r_hist===null?null:row.r_hist*100,"%")],["Historical adjustment (k)",row.r_hist===null?"Omitted":euro(row.k)],["Score before adjustments",modelNumber(row.h_antes_de_ajustes)],["Robust arrears index",modelNumber(row.mora_indice," / 1",3)],["Arrears reduction",modelNumber(row.penalizacion_mora_puntos," points")],["Debt multiplier",modelNumber(row.multiplicador_deuda,"×",3)],["Debt multiplier reduction",modelNumber(row.penalizacion_multiplicador_puntos," points")],["Returned health score",modelNumber(row.health_score)]].map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl><details className="source-records"><summary>Formula and parameters</summary><div className="model-formula"><p>H = 100 × (C6 + cushion + k × historical ratio) / (C6 + cushion + T6_effective + k)</p><p>T6_effective = P6 + D6 + service shortfall over the window + overdue obligations at the cutoff</p><p>Final score = H × (1 − beta × robust arrears index) × debt multiplier</p><p>k = {row.k} EUR · alpha = {row.alpha} · beta = {row.beta}. The cash cushion is capped at alpha × T6_effective. Unknown arrears or debt multipliers apply no adjustment. k is omitted when the historical ratio is undefined. The displayed score comes directly from the saved model output.</p></div></details><h2 className="mt-6">What limits this assessment</h2><ul className="model-reasons">{row.reasons.map(reason=><li key={reason}>{modelReason(reason)}</li>)}{!row.reasons.length && <li>No additional reason codes were returned.</li>}</ul>{row.p6===0 && row.health_score!==null && <p className="model-note">No operating payments were identified, but positive overdue obligations provide evidence for a v4 rating. Missing payments must not be read as perfect financial health.</p>}</section>
        <aside className="metric-explanation" aria-label="Supporting model inputs"><section><span className="eyebrow">Cash movements</span><h2>Reconstructed from the anchor</h2><dl className="metric-equation"><div><dt>Reconstructed cash</dt><dd>{euro(row.cash?.saldo_reversa_eur)}</dd></div><div><dt>This month’s net movement</dt><dd>{euro(row.cash?.flujo_neto)}</dd></div><div><dt>Anchor balance · 1 Sept 2026</dt><dd>{euro(row.cash?.saldo_ancla_eur)}</dd></div><div><dt>Estimated coverage</dt><dd>{modelNumber(row.cash?.meses_de_cobertura_reversa," months")}</dd></div></dl><p className="small muted">Cash is reconstructed backwards from the 1 September 2026 snapshot using subsequent known movements. It is not a bank balance observed at this cutoff or usable cash today. Missing anchors or FX amounts leave gaps.</p></section><section><span className="eyebrow">Payment timing</span><h2>Obligations due at this cutoff</h2><dl className="metric-equation"><div><dt>Known supplier exposure</dt><dd>{euro(row.payment?.pago_exposicion_eur)}</dd></div><div><dt>Overdue at cutoff</dt><dd>{euro(row.payment?.pago_vencido_eur)}</dd></div><div><dt>Robust arrears index</dt><dd>{modelNumber(row.mora_indice," / 1",3)}</dd></div><div><dt>Debt multiplier</dt><dd>{modelNumber(row.multiplicador_deuda,"×",3)}</dd></div></dl><p className="small muted">The index measures weighted delay severity and persistence, not the percentage of invoices overdue. Missing evidence does not imply zero arrears.</p></section></aside>
      </div></section>}
      {scoreDate && <nav className="health-adjacent" aria-label="Other assessments">{previous?<Link className="button secondary" href={scoreHref(previous.as_of)}><ArrowLeft size={16} aria-hidden/>{date(previous.as_of,true)}</Link>:<span/>}{next&&<Link className="button secondary" href={scoreHref(next.as_of)}>{date(next.as_of,true)}<ArrowRight size={16} aria-hidden/></Link>}</nav>}
    </>}
    <section className="card model-provenance" id="evidence"><h2>Source data and model status</h2><p className="small muted">The challenge dataset is synthetic. These are the published v4 model outputs, with provisional parameters and known limitations; this is not a validated credit rating.</p><details><summary>Inspect imported sources and model limitations</summary><div className="model-source-list">{data.provenance.files.map(source=><div key={source.table}><strong>{source.path}</strong><span>{source.rows.toLocaleString("en-GB")} records · SHA-256 {source.sha256}</span></div>)}</div><p className="small muted">Imported {data.provenance.imported_at} · source commit {data.provenance.source_revision}</p><p className="small muted">{data.provenance.model_summary.advertencia}</p><ul className="model-reasons">{data.provenance.model_summary.limitaciones.map(reason=><li key={reason}>{reason}</li>)}</ul></details></section>
  </div>;
}
