"use client";
import Link from "next/link";
import { ArrowLeft, ArrowRight, Activity, Database } from "lucide-react";
import { date, money } from "../lib/format";
import { healthHref } from "../lib/health";
import type { CompanySummary, ModelAssessment, ModelRecord } from "../lib/types";

export const modelNumber = (value: number | null | undefined, suffix = "") => value == null ? "Not available" : `${new Intl.NumberFormat("en-GB", { maximumFractionDigits: 1 }).format(value)}${suffix}`;
const euro = (value: number | null | undefined) => value == null ? "Not available" : money(Math.round(value * 100), "EUR");
const confidence: Record<string, string> = { alta: "High", media: "Medium", baja: "Low", ninguna: "None" };
export function modelReason(reason: string) {
  const unknown = reason.match(/^([cpd])_eur_desconocido_en_(\d+)_meses$/);
  if (unknown) return `${({ c: "Collections", p: "Operating payments", d: "Debt service" } as Record<string, string>)[unknown[1]]} could not be fully determined in ${unknown[2]} month(s) of the window.`;
  return ({ sin_colchon_estimado: "No cash cushion could be estimated.", sin_mora_observable: "Payment arrears were not observable; no arrears adjustment was applied.", colchon_saturado: "The cash cushion reached the model's cap.", denominador_nulo: "No calculable flow ratio for this window.", sin_actividad_de_caja_observada: "No cash-account activity was observed.", ventana_parcial: "The assessment uses fewer than six months of history.", r_hist_indefinida: "The historical ratio was undefined; the history adjustment was omitted.", sin_actividad_en_ventana: "No cash activity was observed in this window." } as Record<string,string>)[reason] ?? reason;
}
function ScoreChart({ records, company }: { records: ModelRecord[]; company: string }) {
  const x = (index: number) => 42 + index * 920 / Math.max(1, records.length - 1);
  const y = (score: number) => 218 - score * 1.9;
  const path = records.map((row, index) => row.health_score === null ? "" : `${index && records[index - 1].health_score !== null ? "L" : "M"}${x(index)},${y(row.health_score)}`).join(" ");
  return <div className="model-chart"><svg viewBox="0 0 1000 258" role="img" aria-labelledby="model-chart-title model-chart-description"><title id="model-chart-title">Monthly health score history</title><desc id="model-chart-description">Saved model ratings from 0 to 100. Gaps mean no score was returned. Select a dated rating below for its explanation.</desc>{[0,25,50,75,100].map(value => <g key={value}><line x1="42" x2="962" y1={y(value)} y2={y(value)} stroke="var(--line)"/><text x="30" y={y(value)+4} textAnchor="end">{value}</text></g>)}<path d={path} fill="none" stroke="var(--accent)" strokeWidth="2.5"/>{records.map((row,index) => row.health_score === null ? null : <a key={row.as_of} href={healthHref(company,row.as_of)} aria-label={`${date(row.as_of,true)}: score ${modelNumber(row.health_score)}`}><circle cx={x(index)} cy={y(row.health_score)} r="7" fill="var(--surface)" stroke="var(--accent)" strokeWidth="2"/></a>)}{records.filter((_,index) => index===0 || index===records.length-1 || index%6===0).map(row => <text key={row.as_of} x={x(records.indexOf(row))} y="246" textAnchor={row===records.at(-1)?"end":"start"}>{date(row.as_of,true)}</text>)}</svg><p className="chart-note">Monthly observations. Missing ratings stay empty; no daily scores are interpolated.</p></div>;
}

export function ModelDashboard({ data, scoreDate, companies, onCompany }: { data: ModelAssessment; scoreDate?: string; companies: CompanySummary[]; onCompany: (id: string) => void }) {
  const row = scoreDate ? data.records.find(row => row.as_of === scoreDate) : data.records.at(-1);
  const scoreHref = (day: string) => healthHref(data.company.id,day);
  const selectedIndex = row ? data.records.indexOf(row) : -1;
  const previous = data.records[selectedIndex - 1];
  const next = data.records[selectedIndex + 1];
  const delta = row?.health_score != null && previous?.health_score != null ? row.health_score - previous.health_score : null;
  return <div className="model-dashboard">
    <header className="page-heading"><div><div className="eyebrow mb-2">Published model assessments</div><h1>{scoreDate ? "The story behind this rating." : "Your financial health, over time."}</h1><p className="muted mt-2">{data.company.name} · {data.company.group} · model inputs in EUR</p></div>{scoreDate && <Link className="button secondary" href={`/dashboard?company=${encodeURIComponent(data.company.id)}`}><ArrowLeft size={16} aria-hidden/>Overview</Link>}</header>
    <div className="context-row"><label className="sr-only" htmlFor="model-company">Company</label><select id="model-company" value={data.company.id} onChange={event=>onCompany(event.target.value)}>{companies.map(company=><option key={company.id} value={company.id}>{company.name}</option>)}</select><span className="badge accent"><Database size={13} aria-hidden/>X-Ray dataset</span><span className="small muted">{data.records.length} monthly assessments</span>{scoreDate && <><label className="sr-only" htmlFor="model-date">Assessment date</label><select id="model-date" value={row?.as_of ?? ""} onChange={event=>window.location.assign(scoreHref(event.target.value))}>{!row && <option value="">Choose an assessment</option>}{[...data.records].reverse().map(record=><option key={record.as_of} value={record.as_of}>{date(record.as_of,true)} · {modelNumber(record.health_score)}</option>)}</select></>}</div>
    {!row ? <section className="card metric-intro"><h2>No assessment for this date</h2><p>The model output is monthly. Choose a saved month-end assessment above.</p></section> : <>
      <section className="stats-grid model-stats" aria-label="Published assessment summary"><article className="stat-card"><div><span>Health score · {date(row.as_of)}</span><Activity size={17} aria-hidden/></div><Link className="model-score-link" href={scoreHref(row.as_of)}><strong className="stat-value num">{modelNumber(row.health_score)}</strong>{row.health_score !== null && <span> / 100</span>}<ArrowRight size={16} aria-hidden/></Link><p>{delta === null ? "No comparable previous score" : `${delta > 0 ? "+" : ""}${modelNumber(delta)} points since ${date(previous.as_of)}`}</p></article>{[["Known collections",row.c6],["Known operating payments",row.p6],["Known debt service",row.d6]].map(([label,value])=><article className="stat-card" key={String(label)}><div><span>{label}</span></div><strong className="stat-value num">{euro(value as number|null)}</strong><p>Across the {row.n_meses_ventana}-month model window</p></article>)}</section>
      <p className="model-context small muted">{row.version} · {date(row.as_of,true)} · Reported confidence: <strong>{confidence[row.confidence] ?? row.confidence}</strong>. Known subtotals can be incomplete; inspect the model reasons.</p>
      {!scoreDate ? <><section className="card"><div className="card-heading"><div><h2>Health score history</h2><p className="small muted mt-1">Select a rating to inspect its recorded inputs and explanation.</p></div></div><ScoreChart records={data.records} company={data.company.id}/><div className="model-dates">{data.records.map(record=><Link key={record.as_of} href={scoreHref(record.as_of)}><strong className="num">{record.health_score === null ? "No score" : modelNumber(record.health_score)}</strong><span>{date(record.as_of,true)}</span></Link>)}</div></section><p className="model-context small muted">Forecasting and planning need a verified opening cash balance and dated future obligations. This dataset supplies historical model outputs.</p></> : <section className="card health-assessment-card"><div className="metric-columns">
        <section className="metric-evidence"><div className="metric-section-heading"><h2>How the model reached this score</h2><span className="badge">{row.n_meses_ventana} months</span></div><p className="small muted">The model combines known collections, operating payments and debt service with a capped cash cushion and the company’s own historical ratio. Payment arrears can reduce the resulting rating.</p><dl className="metric-equation">{[["Known collections (C6)",euro(row.c6)],["Operating payments (P6)",euro(row.p6)],["Debt service (D6)",euro(row.d6)],["Combined known payments (T6)",euro(row.t6)],["Applicable cash cushion",euro(row.colchon_aplicable)],["Own historical collection ratio",modelNumber(row.r_hist===null?null:row.r_hist*100,"%")],["Historical adjustment (k)",row.r_hist===null?"Omitted":euro(row.k)],["Score before arrears",modelNumber(row.h_antes_de_mora)],["Arrears reduction",modelNumber(row.penalizacion_mora_puntos," points")],["Returned health score",modelNumber(row.health_score)]].map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl><details className="source-records"><summary>Formula and parameters</summary><div className="model-formula"><p>H = 100 × (C6 + cushion + k × historical ratio) / (C6 + cushion + T6 + k)</p><p>Final score = H × (1 − beta × payment arrears ratio)</p><p>k = {row.k} EUR · alpha = {row.alpha} · beta = {row.beta}. k is omitted when the historical ratio is undefined. The displayed score comes directly from the saved model output.</p></div></details><h2 className="mt-6">What limits this assessment</h2><ul className="model-reasons">{row.reasons.map(reason=><li key={reason}>{modelReason(reason)}</li>)}{!row.reasons.length && <li>No additional reason codes were returned.</li>}</ul>{row.p6===0 && row.health_score!==null && <p className="model-note">No operating payments were identified in this window. This published model can still return a rating, including 100; that does not establish perfect financial health.</p>}</section>
        <aside className="metric-explanation" aria-label="Supporting model inputs"><section><span className="eyebrow">Cash movements</span><h2>Relative to the observed start</h2><dl className="metric-equation"><div><dt>Cumulative movement</dt><dd>{euro(row.cash?.posicion_acumulada)}</dd></div><div><dt>This month’s net movement</dt><dd>{euro(row.cash?.flujo_neto)}</dd></div><div><dt>Observed start</dt><dd>{row.cash ? date(row.cash.mes_origen.slice(0,10),true):"Not available"}</dd></div><div><dt>Estimated coverage</dt><dd>{modelNumber(row.cash?.meses_de_cobertura," months")}</dd></div></dl><p className="small muted">This is cumulative movement since the first observed month, not a bank balance or usable cash today.</p></section><section><span className="eyebrow">Payment timing</span><h2>Obligations due at this cutoff</h2><dl className="metric-equation"><div><dt>Amount due</dt><dd>{euro(row.payment?.debido_eur)}</dd></div><div><dt>Overdue at cutoff</dt><dd>{euro(row.payment?.en_mora_en_el_corte_eur)}</dd></div><div><dt>Payment arrears ratio</dt><dd>{modelNumber(row.mora_ratio===null?null:row.mora_ratio*100,"%")}</dd></div><div><dt>Average paid delay</dt><dd>{modelNumber(row.payment?.retraso_medio_dias_pagado," days")}</dd></div></dl><p className="small muted">Unavailable inputs stay unknown. Missing payment history does not imply zero arrears.</p></section></aside>
      </div></section>}
      {scoreDate && <nav className="health-adjacent" aria-label="Other assessments">{previous?<Link className="button secondary" href={scoreHref(previous.as_of)}><ArrowLeft size={16} aria-hidden/>{date(previous.as_of,true)}</Link>:<span/>}{next&&<Link className="button secondary" href={scoreHref(next.as_of)}>{date(next.as_of,true)}<ArrowRight size={16} aria-hidden/></Link>}</nav>}
    </>}
    <section className="card model-provenance" id="evidence"><h2>Source data and model status</h2><p className="small muted">The challenge dataset is synthetic. These are the published v3 model outputs, with provisional parameters and known limitations; this is not a validated credit rating.</p><details><summary>Inspect imported sources and model limitations</summary><div className="model-source-list">{data.provenance.files.map(source=><div key={source.table}><strong>{source.path}</strong><span>{source.rows.toLocaleString("en-GB")} records · SHA-256 {source.sha256}</span></div>)}</div><p className="small muted">Imported {data.provenance.imported_at} · source commit {data.provenance.source_revision}</p><p className="small muted">{data.provenance.model_summary.advertencia}</p><ul className="model-reasons">{data.provenance.model_summary.limitaciones.map(reason=><li key={reason}>{reason}</li>)}</ul></details></section>
  </div>;
}
